# Site settings
title: Pangeo Data
header-img: img/mountain-beach-cropped.jpg
# email: your-email@yourdomain.com
copyright_name: Pangeo Data
description: "A community effort for big data geoscience"
url: "http://pangeo-data.github.io"
# twitter_username: SBootstrap
github_username:  pangeo-data
# facebook_username:  StartBootstrap
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-redirect-from]

collections:
  design_docs:
    output: true
    name: "Design Documents"
